In [1]:
import cv2
import numpy as np

In [2]:
# input image
image = cv2.imread("buga.png")
cv2.imshow("original image", image)
cv2.waitKey(0)

# reducing the original image by half
half_scaled = cv2.resize(image, dsize = None, fx = 0.5, fy = 0.5)
cv2.imshow("half scaled image", half_scaled)
cv2.waitKey(0)

# increasing image scaled with interpolation
increse_scale = cv2.resize(image, dsize = None, fx = 1.5, fy= 1.5, interpolation = cv2.INTER_AREA)
cv2.imshow("Increased scale", increse_scale)
cv2.waitKey(0)

# skewing an image by including 'dsize' parameter
scew = cv2.resize(image, dsize = (760, 150), interpolation = cv2.INTER_AREA)
cv2.imshow("scew", scew)
cv2.waitKey(0)








cv2.destroyAllWindows()

### Scaling by image pyramid
 Image pyramids comes handy. The pyrUp() function increases the size to double of its original size and pyrDown() function decreases the size to half.


In [4]:
image = cv2.imread("buga.png")
cv2.imshow("original image", image)
cv2.waitKey(0)
# scaling up
large = cv2.pyrUp(image)
cv2.imshow("large pyramid", large)
cv2.waitKey(0)

# scaling down
small = cv2.pyrDown(image)
cv2.imshow("scaaling down pyramid", small)
cv2.waitKey(0)

cv2.destroyAllWindows()

### Rotation and Flip using OpenCV
cv2.getRotationMatrix2D(rotation_center_x, rotation_center_y, angle of rotation, scale)

In [6]:
import cv2
import numpy as np 

In [7]:
# geting the shape of the input image 
image = cv2.imread("buga.png")

# image.shape prints out the shape of an image 
# image.shape[:2] output the first 2 columns
image.shape, image.shape[:2]

((373, 557, 3), (373, 557))

In [8]:
# loading the input image 
image = cv2.imread("buga.png")
cv2.imshow("original image", image)

# getting the height and width of the image 
height, width = image.shape[:2]

# dividing height and width by 2 to rotate the image about it center. we use the rotation matrx
rotation_mat = cv2.getRotationMatrix2D( (height/2, width/2), 45, 1)

rotate_image_output = cv2.warpAffine(image, rotation_mat, (width, height))
cv2.imshow("rotated image", rotate_image_output)

cv2.waitKey(0)
cv2.destroyAllWindows()


### Flipping an image horizontally or vertically 
cv2.flip(image, flip_code(1 or 0))

In [10]:
image = cv2.imread("buga.png")
cv2.imshow("original image", image)
cv2.waitKey(0)

# flipping vertically 
v_flip = cv2.flip(image, 0)
cv2.imshow("vertical flip", v_flip)
cv2.waitKey(0)

# horizontal flip
h_flip = cv2.flip(image, 1)
cv2.imshow("horizontal flip", h_flip)
cv2.waitKey(0)

cv2.destroyAllWindows()

### Image Translation 
this is moving image from one location to another
in image translation, translation matrix is used 

#### Translation Matrix elements
#####           | 1 0 Tx |
#####    | 0 1 Ty  |

In [12]:
import cv2 
import numpy as np

# load input image 
image =  cv2.imread("buga.png")
cv2.imshow("original image", image)

# extracting height and width of the image 
height, width = image.shape[:2]
print(height, width)
print("==========")

# translate the height and width of the image to 1/4
height_forth, width_forth = height/4, width/4

# applying translation matrix
T = np.float32([[1, 0, height_forth], [0, 1, width_forth]])

# let us view the translation matrix
print(T)

# using wrapAffine to transform the image using the translation matrix, T
translation = cv2.warpAffine(image, T, (width, height))
cv2.imshow("Translated image", translation)
cv2.waitKey(0)
cv2.destroyAllWindows()

373 557
[[  1.     0.    93.25]
 [  0.     1.   139.25]]


In [22]:
for x in range(0,4):
    print(x)

0
1
2
3


 ### Adjusting image brightness

In [39]:
import cv2
import numpy as np

# load original image
img = cv2.imread("bettle.webp")
cv2.imshow("original image", img)

# creating a matrix of ones using the image dimensions as our matrix dimension
intensity_mat = np.ones(img.shape, dtype = "uint8") * 90

# print  the intensity matrix
print(intensity_mat)

# add intensity matrix to the input image in order to increase the brightness
bright_img = cv2.add(img, intensity_mat)
cv2.imshow("bright image", bright_img)

# subtract to darken the image 
dark = cv2.subtract(img, intensity_mat)
cv2.imshow("darken image", dark)

cv2.waitKey(0)
cv2.destroyAllWindows()

[[[90 90 90]
  [90 90 90]
  [90 90 90]
  ...
  [90 90 90]
  [90 90 90]
  [90 90 90]]

 [[90 90 90]
  [90 90 90]
  [90 90 90]
  ...
  [90 90 90]
  [90 90 90]
  [90 90 90]]

 [[90 90 90]
  [90 90 90]
  [90 90 90]
  ...
  [90 90 90]
  [90 90 90]
  [90 90 90]]

 ...

 [[90 90 90]
  [90 90 90]
  [90 90 90]
  ...
  [90 90 90]
  [90 90 90]
  [90 90 90]]

 [[90 90 90]
  [90 90 90]
  [90 90 90]
  ...
  [90 90 90]
  [90 90 90]
  [90 90 90]]

 [[90 90 90]
  [90 90 90]
  [90 90 90]
  ...
  [90 90 90]
  [90 90 90]
  [90 90 90]]]


### how to crop an image using indexing

In [4]:
import cv2
import numpy as np

In [14]:
# importing the image 
img = cv2.imread("bettle.webp")

# extracting the height and width of the image
height, width = img.shape[:2]
print("height of image", height)
print("width of image", width)

# extract the pixel starting point you want to crop (starting from the left)\
start_row, start_col = int(height * 0.2), int(width * 0.2)

# extracting the row and column you want to end the cropping 
end_row, end_col = int(height * 0.8), int(width * 0.8)

# using the indexing method to crop the image 
cropped_img = img[start_row: end_row, start_col:end_col]
# printing the shape of the cropped image 
print("cropped image shape: ", cropped_img.shape)

# displaying both original and cropped
cv2.imshow("original image", img)
cv2.waitKey(0)
cv2.imshow("cropped image", cropped_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

height of image 1024
width of image 1024
cropped image shape:  (615, 615, 3)


### image masking 
This involves hiding some portion of the image editing where it hides some portions of an image. 
this is doen basically by adding shapes to the image and using bit wise operators (logic condition)

In [3]:
import cv2
import numpy as np

In [5]:
# Draw a greyscale (number of channel = 1) square
square_image = np.zeros((400, 400, 1), np.uint8)
cv2.rectangle(square_image, (70, 70), (300, 300), 255, -2)
cv2.imshow("Square", square_image)
cv2.waitKey(0)

# Draw greyscale (number of channel = 1)
circle = np.zeros((400, 400, 1), np.uint8)
cv2.circle(circle, (300, 300), 70, (255,0,0), -1)
cv2.imshow("Circle", circle)
cv2.waitKey(0)


cv2.destroyAllWindows()


#### using bit wise operations on the shapes

In [8]:
# showing the region where both square and circle intersect
AND_operations = cv2.bitwise_and(square_image, circle)
cv2.imshow("AND operation", AND_operations)
cv2.waitKey(0)

# showing the region where either the square or circle is
OR_operation = cv2.bitwise_or(square_image, circle)
cv2.imshow("OR operation", OR_operation)
cv2.waitKey(0)

# showing the region where either circle or square exists (XOR)
XOR_operation = cv2.bitwise_xor(square_image, circle)
cv2.imshow("XOR operation", XOR_operation )
cv2.waitKey(0)

# showing the region that is not part of square i.e inverse of the square image
NOT_operation = cv2.bitwise_not(square_image)
cv2.imshow("NOT operation", NOT_operation)
cv2.waitKey(0)

cv2.destroyAllWindows()


In [ ]:
### Bluring an image
